# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Geo-GoogleEarth-Pluggable
version:      0.01
version_from: lib/Geo/GoogleEarth/Pluggable.pm
installdirs:  site
requires:
    Scalar::Util:                  0
    strict:                        0
    Test::Simple:                  0.44
    warnings:                      0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30
