Name:           perl-Geo-GoogleEarth-Pluggable
Version:        0.14
Release:        1%{?dist}
Summary:        Generates GoogleEarth Documents
License:        BSD
Group:          Development/Libraries
URL:            http://search.cpan.org/dist/Geo-GoogleEarth-Pluggable/
Source0:        http://www.cpan.org/modules/by-module/Geo/Geo-GoogleEarth-Pluggable-%{version}.tar.gz
BuildRoot:      %{_tmppath}/%{name}-%{version}-%{release}-root-%(%{__id_u} -n)
BuildArch:      noarch
BuildRequires:  perl(ExtUtils::MakeMaker)
BuildRequires:  perl(Test::Simple) >= 0.44
Requires:       perl(Archive::Zip)
Requires:       perl(IO::Scalar)
Requires:       perl(Method::Autoload)
Requires:       perl(Module::Pluggable)
Requires:       perl(Test::Simple) >= 0.44
Requires:       perl(XML::LibXML::LazyBuilder)
Requires:       perl(:MODULE_COMPAT_%(eval "`%{__perl} -V:version`"; echo $version))

%description
Geo::GoogleEarth::Pluggable is a Perl object oriented interface that allows
for the creation of XML documents that can be used with Google Earth.

%prep
%setup -q -n Geo-GoogleEarth-Pluggable-%{version}

%build
%{__perl} Makefile.PL INSTALLDIRS=vendor
make %{?_smp_mflags}

%install
rm -rf $RPM_BUILD_ROOT

make pure_install PERL_INSTALL_ROOT=$RPM_BUILD_ROOT

find $RPM_BUILD_ROOT -type f -name .packlist -exec rm -f {} \;
find $RPM_BUILD_ROOT -depth -type d -exec rmdir {} 2>/dev/null \;

%{_fixperms} $RPM_BUILD_ROOT/*

%check
make test

%clean
rm -rf $RPM_BUILD_ROOT

%files
%defattr(-,root,root,-)
%doc Changes LICENSE README Todo
%{perl_vendorlib}/*
%{_mandir}/man3/*

%changelog
* Mon Dec 27 2010 Michael R. Davis (mdavis@stopllc.com) 0.12-1
- Specfile autogenerated by cpanspec 1.78.
